### ISSUE TITLE
next() throwing error randomly

### ISSUE THREAD

**Issue by laggingreflex** [fullstackers/socket.io-events#8]
I have narrowed down my code to following for debugging 

```
router.on(function(socket, arguments, next) {
    next();
});
```

The `next()` in there keeps throwing the following error

There's nothing in the error stack that points to my application code, which makes me thing maybe it's error in the module itself?

```
events.js:74
        throw TypeError('Uncaught, unspecified "error" event.');
              ^
TypeError: Uncaught, unspecified "error" event.
    at TypeError (<anonymous>)
    at Socket.emit (events.js:74:15)
    at next (C:\~\node_modules\socket.io-events\lib\router.js:130:20)
    at step (C:\~\node_modules\socket.io-events\lib\router.js:188:9)
    at Router.router.onRoute (C:\~\node_modules\socket.io-events\lib\router.js:191:7)
    at Socket.Router.router.onEvent [as onevent] (C:\~\node_modules\socket.io-events\lib\router.js:72:12)
    at Socket.onpacket (C:\~\node_modules\socket.io\lib\socket.js:287:12)
    at Client.ondecoded (C:\~\node_modules\socket.io\lib\client.js:185:14)
    at Decoder.Emitter.emit (C:\~\node_modules\socket.io\node_modules\socket.io-parser\node_modules\component-emitter\index.js:134:20)
    at Decoder.add (C:\~\node_modules\socket.io\node_modules\socket.io-parser\index.js:233:12)
    at Client.ondata (C:\~\node_modules\socket.io\lib\client.js:170:16)
    at Socket.emit (events.js:95:17)
    at Socket.onPacket (C:\~\node_modules\socket.io\node_modules\engine.io\lib\socket.js:99:14)
    at WebSocket.emit (events.js:117:20)
    at WebSocket.Transport.onPacket (C:\~\node_modules\socket.io\node_modules\engine.io\lib\transport.js:91:8)
    at WebSocket.Transport.onData (C:\~\node_modules\socket.io\node_modules\engine.io\lib\transport.js:102:8)
    at WebSocket.onData (C:\~\node_modules\socket.io\node_modules\engine.io\lib\transports\websocket.js:75:30)
    at WebSocket.emit (events.js:98:17)
    at Receiver.self._receiver.ontext (C:\~\node_modules\socket.io\node_modules\engine.io\node_modules\ws\lib\WebSocket.js:697:10)
    at Receiver.opcodes.1.finish (C:\~\node_modules\socket.io\node_modules\engine.io\node_modules\ws\lib\Receiver.js:397:14)
    at Receiver.expectHandler (C:\~\node_modules\socket.io\node_modules\engine.io\node_modules\ws\lib\Receiver.js:378:33)
    at Receiver.add (C:\~\node_modules\socket.io\node_modules\engine.io\node_modules\ws\lib\Receiver.js:93:24)
    at Socket.firstHandler (C:\~\node_modules\socket.io\node_modules\engine.io\node_modules\ws\lib\WebSocket.js:678:22)
    at Socket.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:748:14)
    at Socket.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:410:10)
    at emitReadable (_stream_readable.js:406:5)
    at readableAddChunk (_stream_readable.js:168:9)
    at Socket.Readable.push (_stream_readable.js:130:10)
    at TCP.onread (net.js:528:21)
```

**Comment by NathanGRomano** [comment]
Thanks I will check it out as soon as I can!

Sent from my iPhone

On Oct 25, 2014, at 10:17 AM, laggingreflex notifications@github.com
wrote:

I have narrowed down my code to following for debugging

router.on(function(socket, arguments, next) {
    next();
});

The next() in there keeps throwing the following error

There's nothing in the error stack that points to my application code,
which makes me thing maybe it's error in the module itself?

events.js:74
        throw TypeError('Uncaught, unspecified "error" event.');
              ^
TypeError: Uncaught, unspecified "error" event.
    at TypeError (<anonymous>)
    at Socket.emit (events.js:74:15)
    at next (C:~\node_modules\socket.io-events\lib\router.js:130:20)
    at step (C:~\node_modules\socket.io-events\lib\router.js:188:9)
    at Router.router.onRoute
(C:~\node_modules\socket.io-events\lib\router.js:191:7)
    at Socket.Router.router.onEvent [as onevent](C:~node_modulessocket.io-eventslibrouter.js:72:12)
    at Socket.onpacket (C:~\node_modules\socket.io\lib\socket.js:287:12)
    at Client.ondecoded (C:~\node_modules\socket.io\lib\client.js:185:14)
    at Decoder.Emitter.emit
(C:~\node_modules\socket.io\node_modules\socket.io-parser\node_modules\component-emitter\index.js:134:20)
    at Decoder.add
(C:~\node_modules\socket.io\node_modules\socket.io-parser\index.js:233:12)
    at Client.ondata (C:~\node_modules\socket.io\lib\client.js:170:16)
    at Socket.emit (events.js:95:17)
    at Socket.onPacket
(C:~\node_modules\socket.io\node_modules\engine.io\lib\socket.js:99:14)
    at WebSocket.emit (events.js:117:20)
    at WebSocket.Transport.onPacket
(C:~\node_modules\socket.io\node_modules\engine.io\lib\transport.js:91:8)
    at WebSocket.Transport.onData
(C:~\node_modules\socket.io\node_modules\engine.io\lib\transport.js:102:8)
    at WebSocket.onData
(C:~\node_modules\socket.io\node_modules\engine.io\lib\transports\websocket.js:75:30)
    at WebSocket.emit (events.js:98:17)
    at Receiver.self._receiver.ontext
(C:~\node_modules\socket.io\node_modules\engine.io\node_modules\ws\lib\WebSocket.js:697:10)
    at Receiver.opcodes.1.finish
(C:~\node_modules\socket.io\node_modules\engine.io\node_modules\ws\lib\Receiver.js:397:14)
    at Receiver.expectHandler
(C:~\node_modules\socket.io\node_modules\engine.io\node_modules\ws\lib\Receiver.js:378:33)
    at Receiver.add
(C:~\node_modules\socket.io\node_modules\engine.io\node_modules\ws\lib\Receiver.js:93:24)
    at Socket.firstHandler
(C:~\node_modules\socket.io\node_modules\engine.io\node_modules\ws\lib\WebSocket.js:678:22)
    at Socket.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:748:14)
    at Socket.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:410:10)
    at emitReadable (_stream_readable.js:406:5)
    at readableAddChunk (_stream_readable.js:168:9)
    at Socket.Readable.push (_stream_readable.js:130:10)
    at TCP.onread (net.js:528:21)

—
Reply to this email directly or view it on GitHub
https://github.com/turbonetix/socket.io-events/issues/8.

**Comment by NathanGRomano** [comment]
I wrote this test, however, it does work.  It is based on the example you gave me. Is there any other information you can provide?

``` javascript
var router = require('./')();
router.on(function (sock, args, next) {
  console.log(args);
  next();
});
var io = require('socket.io')(3000);
io.use(router);
setTimeout(function () {
  var sock = require('socket.io-client').connect('ws://localhost:3000');
  sock.on('connect', function () {
    sock.emit('say');
  }); 
  sock.on('say', function () {
    process.exit(0);
  }); 
}, 1000);
```

**Comment by laggingreflex** [comment]
It turned out to be application code error after all. So rry for wasting your time, it's embarassing :}. Good on you for being a prompt maintainer though :+1:

**Comment by NathanGRomano** [comment]
I appreciate it.  If you have any questions or need help let me know.
